apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: go-tfzljqlb
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/go-tfzljqlb:256478f807bc50813cb0230dda0ebb4f078dae5f@sha256:d35fb544d3a7828ee2c1f0e12a64aa0081bc1ec20caa52adf3d6ae53ebd79ca0
          name: container-image
